[package]
name = "fluent-uri"
version = "0.1.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"

[dependencies]
beef = "0.5.1"

# Commented out to reduce compile time.

# [[bench]]
# name = "bench"
# harness = false

# [dev-dependencies]
# criterion = "0.3"
# url = "2.2.2"
# uriparse = "0.6.4"