on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: test with no feature
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
